#!/usr/bin/env python3
"""
TASK 6 (Owner directive 2026-07-20: "make MASTER_INDEX.yaml logical for
you or any AI to work... stepwise, exact input/output, properly
documented"). Mechanically generates a compact, scannable quick_reference
list -- id + path + status + a one-line summary auto-extracted from each
registry entry's own first prose field -- rather than hand-summarizing 41
entries under time pressure (which risks inconsistent quality/accuracy).
Software-driven per the directive's own "modern software already has
packages, use them" instruction: this is a mechanical extraction, not an
AI-authored redescription.

Priority order for the one-line summary field, first match wins:
scope, purpose, finding, decision, content -- these are the fields this
file's own registries actually use for their opening description, found
by inspection, not guessed.

Run: python3 generate_quick_reference.py <path-to-MASTER_INDEX.yaml>
Prints the quick_reference YAML block to stdout -- paste it in manually
(deliberately not auto-inserting/rewriting the file, to keep a human/AI
review step before this mechanical output becomes part of the canonical
file).
"""
import os
import sys
import yaml

SUMMARY_FIELD_PRIORITY = ["scope", "purpose", "finding", "decision", "content"]
GENERATED_DIR = "/opt/veridian/ai-os/generated"


def first_line(text, max_len=140):
    text = " ".join(text.split())  # collapse whitespace/newlines
    if len(text) <= max_len:
        return text
    return text[:max_len].rsplit(" ", 1)[0] + "..."


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else "MASTER_INDEX.yaml"
    with open(path, encoding="utf-8") as f:
        doc = yaml.safe_load(f)

    entries = []
    for reg in doc.get("registries", []):
        rid = reg.get("id", "UNKNOWN")
        status = reg.get("status")
        status_short = first_line(status, 60) if isinstance(status, str) else "unspecified"
        path_val = reg.get("path")
        if isinstance(path_val, dict):
            path_val = None
        summary = None
        for field in SUMMARY_FIELD_PRIORITY:
            val = reg.get(field)
            if isinstance(val, str) and val.strip():
                summary = first_line(val)
                break
        if summary is None:
            summary = "(no scope/purpose/finding/decision field -- see full entry)"
        entry = {"id": rid, "status": status_short}
        if path_val:
            entry["path"] = path_val
        entry["summary"] = summary
        entries.append(entry)

    header = (
        "quick_reference:\n"
        "  # Mechanically generated by generate_quick_reference.py -- scan this\n"
        "  # list FIRST. Each line: id, status, path (if any), and a one-line\n"
        "  # summary auto-extracted from the entry's own scope/purpose/finding/\n"
        "  # decision field. Only read the full entry under 'registries:' below\n"
        "  # once you've found your match here. Regenerate after adding/editing\n"
        "  # a registry entry -- do not hand-edit this block.\n"
    )
    print(header, end="")
    # yaml.safe_dump handles all quoting/escaping correctly (unlike manual
    # f-string wrapping, which broke on entries whose extracted text itself
    # contained double quotes -- caught by reviewing this script's own
    # output before trusting it, not assumed correct).
    body = yaml.safe_dump(entries, default_flow_style=False, sort_keys=False, allow_unicode=True, width=100)
    indented_body = "".join("  " + line + "\n" for line in body.splitlines())
    print(indented_body, end="")

    # Governance item 36 (documentation_auto_generation, 2026-07-23): also persist
    # to a real file, in addition to the stdout print above (kept as-is -- this
    # script's own docstring reason for not auto-rewriting MASTER_INDEX.yaml itself
    # still applies; this is a separate file, not that one).
    os.makedirs(GENERATED_DIR, exist_ok=True)
    with open(os.path.join(GENERATED_DIR, "generate_quick_reference-latest.yaml"), "w", encoding="utf-8") as f:
        f.write(header + indented_body)


if __name__ == "__main__":
    main()
